config/routes.rb
DevRoom::Application.routes.draw do
  devise_for :users

  get 'room' => 'room#index'

  get 'conversations/:task_id/:user_id' => 'room#start_conversation', as: 'start_conversation'
  delete 'conversations/:id' => 'room#archive_conversation', as: 'archive_conversation' 
  post 'tasks' => 'room#new_task', as: 'new_task'
  post 'messages/:id' => 'room#new_message', as: 'new_message'
  get '/alive' => 'room#alive', as: 'alive'

  root :to => 'landing#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/conversation.rb
class Conversation
  include Mongoid::Document
  include Mongoid::Timestamps

  field :archived, type: Boolean, default: false

  default_scope where(:archived.ne => true)

  has_many :messages
  belongs_to :task
  has_and_belongs_to_many :users
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps

  field :text
  belongs_to :conversation, dependent: :destroy
  belongs_to :user
end

app/models/task.rb
class Task
  include Mongoid::Document
  include Mongoid::Timestamps

  field :description, type: String
  field :resolved, type: Boolean, default: false
  has_one :conversation
  belongs_to :user

  validates :description, presence: true, length: {minimum: 10}
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  field :name
  field :admin, type: Boolean, default: false
  field :online, type: Boolean, default: false

  validates :name, presence: true

  has_many :messages
  has_many :tasks
  has_and_belongs_to_many :conversations

  def self.user_list
    only(:id, :name, :online).as_json
  end

  def self.check_for_inactive_users
    User.each do |u|
      u.update_attribute(:online, false) if (u.updated_at < 2.minutes.ago)
    end
    PrivatePub.publish_to "/users/list", :users => User.user_list
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    update_user_list(true)
    room_path
  end

  def after_sign_out_path_for(resource)
    update_user_list(false)
    root_path
  end
  
  # This action updates the status of current user and then broadcasts user list to everyone
  def update_user_list(status)
    current_user.update_attribute(:online, status)
    PrivatePub.publish_to "/users/list", :users => User.user_list
  end

  protected
 
  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end

  
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.only(:name, :online, :id).all
    @tasks = Task.all.asc(:resolved).desc(:created_at)
    @conversations = current_user.conversations
    update_user_list(true)
  end

  def start_conversation

    # There are 3 possible scenarios
    # 1.) General conversation b/w two persons and we create one and add both participants
    # 2.) Conversation on a task and we create one with both particpants with task assigned
    # 3.) Conversation is already present for a task and we just want to add a new participant to it

    # Get task if any. Cases 2 and 3
    if params[:task_id] != "0"
      task = Task.find(params[:task_id])
      
      # Case 3
      if task.conversation
        @case = 3
        @conversation = task.conversation
        @conversation.users << current_user
      # Case 2
      else
        @conversation = Conversation.new
        @conversation.task = task  
        second_user = User.find(params[:user_id])
        @conversation.users = [current_user, second_user]    
      end
    # Case 1
    else
      @conversation = Conversation.new
      second_user = User.find(params[:user_id])
      @conversation.users = [current_user, second_user]
    end
      
    if @conversation.save
      render
    else
      @error = @conversation.errors.full_messages.join(",")
      render "shared/error"
    end
  end

  def archive_conversation
    @conversation = Conversation.find(params[:id])
    @conversation.update_attributes(archived: true)
  end

  def new_task
    @task = Task.new
    @task.description =  params[:description]
    @task.user = current_user

    if @task.save
      render
    else
      @error = @task.errors.full_messages.join(",")
      render "shared/error"
    end
  end

  def new_message
    @conversation = Conversation.find(params[:id])
    return unless @conversation

    @message = Message.new(conversation: @conversation, user: current_user, text: params[:message][:text])
    if @message.save
      render
    else
      @error = @message.errors.full_messages.join(",")
      render "shared/error"
    end

  end

  def alive
    current_user.touch
    render text: "OK"    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/conversations/_conversation.html.haml
%div{:style => "width:48%; float:left; margin-right:2%;"}
  .pane.conversation{id: "conversation_#{conversation.id}"}
    %p.heading
      = conversation.task.description.truncate(20) rescue "General Chat"
      = link_to archive_conversation_path(conversation), remote: true, method: "delete", confirm: "This will archive the conversation. Continue?" do
        %i.icon-remove.pull-right
      / = conversation.users.map(&:name).join(", ")
    .messages
      - conversation.messages.each do |message|
        = render message
    .new_message
      = form_for 'message', url: new_message_path(conversation), remote: true do |f|
        = f.text_area :text   
        = f.submit "Post", class: "btn btn-success"   

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "DevRoom"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    = render "shared/navbar"
    #user_id.hide= current_user.id if current_user
    .container-fluid#main
      /= bootstrap_flash
      .row-fluid
        .span2
          = yield :sidebar
        .span10
          = yield

    / Javascripts
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield :scripts

app/views/layouts/landing.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title DevRoom
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  %body
    = render "shared/navbar"

    .container-fluid#landing
      .row-fluid
        .span3
        .span3{:style => "border-right: 1px solid #CECBBB;"}
          %h4 Ask for help
          %h4 Offer help
          %h4 Share collective knowledge
          %h4 Get stuff done faster
        .span6
          = render "shared/sign_in"

      .row-fluid
        .span12
          /= bootstrap_flash
          = yield

      .row-fluid      
        .span4
        .span4#why
          %p DevRoom is an attempt to improve conversations among developers at workplaces.

          %p Thanks to the ever changing nature of technology, a single day in the lives of most developers involves learning new things, reading docs, building stuff, breaking stuff and pushing the shiny parts to the world.
          
          %p This experience although enriching in it's own way also has the downside of losing time trying to do the same things over and over again.





        .span4
    / Javascripts
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/messages/_message.html.haml
%p
  %b= message.user.name + ":"
  =message.text
  %em.timestamp.pull-right= message.created_at.to_datetime.strftime('%H:%M')

app/views/room/archive_conversation.js.erb
<% publish_to "/conversations/#{@conversation.id}/archive" do %>
  $('<%= "#conversation_#{j @conversation.id.to_s}}" %>').remove();
<% end %>

app/views/room/index.html.haml
=content_for :sidebar do
  #userlist.pane
    %p.heading Team
    %ul.unstyled
      -@users.each do |user|
        - next if user == current_user
        %li
          - user_status_color = user.online ? 'lightgreen' : 'lightgrey'
          %i.icon-circle{style: "color: #{user_status_color}"}
          - if user.online?
            = link_to user.name, start_conversation_path(0,user.id), remote: true
          -else
            = user.name
          
  .pane
    %p.heading You
    - if current_user
      %h4= current_user.name
      =link_to "Profile", "#", class: "btn btn-success"
      =link_to "Logout", destroy_user_session_path, class: "btn btn-info", method: :delete

.row-fluid
  .span6
    .row-fluid
      = render "tasks/new_task"
      
    #tasks
      = render @tasks

  .span6
    .row-fluid#conversations
      = render @conversations

=content_for :scripts do
  #subscriptions
    = subscribe_to "/users/list"
    = subscribe_to "/tasks/list"
    = subscribe_to "/conversations/#{current_user.id}/active"
    - @conversations.each do |conversation|
      = subscribe_to "/conversations/#{conversation.id}/messages"
      = subscribe_to "/conversations/#{conversation.id}/archive"
    

app/views/room/new_message.js.erb
<% conversation = "#conversation_#{@conversation.id.to_s}" %>

<% publish_to "/conversations/#{@conversation.id}/messages" do %>
  $("<%= conversation %> .messages").append("<%= j render(@message) %>");
<% end %>

$("<%= conversation %> .new_message textarea[name='message[text]']").val('');

app/views/room/new_task.js.erb
<% publish_to "/tasks/list" do %>
  $("#tasks").prepend("<%= j render(@task) %>");
<% end%>
$("textarea[name='description']").val('');

app/views/room/start_conversation.js.erb
<% if @case == 3 %>
  // This is special case. Refer to start_conversation in Room controller for the cases

  // Publish to current user the conversation she was added to
  <% publish_to "/conversations/#{current_user.id}/active" do %>
    $("#conversations").append("<%= j render @conversation %>");
    $("#subscriptions").append('<%= j subscribe_to "/conversations/#{@conversation.id}/messages"%>')  
    $("#subscriptions").append('<%= j subscribe_to "/conversations/#{@conversation.id}/archive"%>')  
  <% end%>
  // Publish to others the removal of existing conv and add it back again to reflect the addition of new user
  <% @conversation.users.each do |user|%>
    <% publish_to "/conversations/#{user.id}/active" do %>
      $("#conversation_<%= j @conversation.id.to_s %>").remove();
      $("#conversations").append("<%= j render @conversation %>");
    <%end%>
  <%end%>

<% else%>
  <% @conversation.users.each do |user|%>
    <% publish_to "/conversations/#{user.id}/active" do %>
      $("#conversations").append("<%= j render @conversation %>");
      $("#subscriptions").append('<%= j subscribe_to "/conversations/#{@conversation.id}/messages"%>')  
      $("#subscriptions").append('<%= j subscribe_to "/conversations/#{@conversation.id}/archive"%>')  
    <%end%>
  <%end%>
<% end%>

app/views/shared/_navbar.html.haml
.navbar
  .navbar-inner
    %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a#logo{href: "/"} 
      =image_tag "logo.png"
      

app/views/shared/_sign_in.html.haml
- if current_user
  %p You are logged In
  %p
    = link_to "Go to Room", room_path, class: "btn btn-primary"
  %p
    = link_to "Sign Out", destroy_user_session_path, class: "btn btn-info"
- else
  = form_for("user", url: user_session_path) do |f|
    %div
      = f.label :email
      = f.email_field :email, autofocus: true
    %div
      = f.label :password
      = f.password_field :password
    %div
      = f.submit "Sign in", class: "btn btn-primary"
  Or    
  = link_to "Sign up", new_user_registration_path

app/views/shared/error.js.erb
$.bootstrapGrowl("<%= j @error%>", {type: 'error'});

app/views/tasks/_new_task.html.haml
.span12.pane
  = form_for "task", url: new_task_path, remote: true do |f|
    %textarea.span12{name: "description", placeholder: "A question you have / A task you're working on / A briefing you need"}
    =submit_tag "Post", class: "btn btn-primary"

app/views/tasks/_task.html.haml
- minutes = ((Time.now - task.created_at)/60).round
- task_color = (minutes > 60)? 75 : 255 - 3*minutes

.row-fluid.task
  = link_to start_conversation_path(task,task.user.id), "data-toggle" => "tooltip", title: "Click to start a conversation on this subject", remote: true, class: "task_link" do
    .span12.pane
      %p= task.description
      %small
        = "by  #{task.user.name}"
        .post_time_of_task= minutes
        minutes ago
  - if task.resolved?
    %a{href:"javascript:void(0)", "data-toggle" => "tooltip", title: "Resolved"}
      %i.icon-ok-sign{style: "color: #3BBC3B;"}
  -else
    %a{href:"javascript:void(0)", "data-toggle" => "tooltip", title: "Unresolved"}
      %i.icon-exclamation-sign.task_status{style: "color: rgba(255, #{task_color}, #{task_color},1)"}

app/views/user/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/